export type Passage = {
  id: string;
  grade: number;
  title: string;
  genre: "fiction" | "nonfiction";
  text: string;
  mainIdea: string;
  supportingDetails: string[];
  theme?: string;
  summary: string;
  vocabulary: { word: string; hint: string; definition: string }[];
  claim?: string;
  evidence?: string[];
};

export const PASSAGES: Passage[] = [
  {
    id: "g3-butterfly",
    grade: 3,
    title: "Monarch Migration",
    genre: "nonfiction",
    text: "Every fall, monarch butterflies travel thousands of miles to Mexico. They fly in large groups and rest on trees together. The journey is long and dangerous, but the butterflies know the way. Scientists still study how they find the same forests year after year.",
    mainIdea: "Monarch butterflies migrate to Mexico each fall.",
    supportingDetails: [
      "They travel thousands of miles.",
      "They rest on trees together.",
      "Scientists study how they find the forests.",
    ],
    summary: "Monarch butterflies migrate long distances to Mexico in fall, resting in groups while scientists study their navigation.",
    vocabulary: [
      { word: "migrate", hint: "move from one place to another for a season", definition: "to travel to a different region seasonally" },
      { word: "journey", hint: "a long trip", definition: "a long trip from one place to another" },
    ],
  },
  {
    id: "g3-lost-key",
    grade: 3,
    title: "The Lost Key",
    genre: "fiction",
    text: "Mia could not find her house key after school. She checked her backpack, her coat pockets, and the front porch. Her neighbor Mr. Lee saw her searching and lent her a spare key. Mia promised to look more carefully next time.",
    mainIdea: "Mia loses her key but gets help from her neighbor.",
    supportingDetails: [
      "She checked her backpack and pockets.",
      "Mr. Lee lent her a spare key.",
      "She promised to be more careful.",
    ],
    theme: "Neighbors help each other in small ways.",
    summary: "Mia loses her house key, searches everywhere, and Mr. Lee helps her with a spare key.",
    vocabulary: [
      { word: "lent", hint: "gave something to borrow", definition: "gave temporarily with expectation of return" },
      { word: "spare", hint: "extra", definition: "kept in reserve; extra" },
    ],
  },
  {
    id: "g3-rain-garden",
    grade: 3,
    title: "Our School Rain Garden",
    genre: "nonfiction",
    text: "Our class planted a rain garden behind the cafeteria. Rain gardens collect water so it soaks into the ground instead of flooding the parking lot. We chose native flowers that attract bees and butterflies. Now the garden is both useful and beautiful.",
    mainIdea: "The class created a rain garden that helps manage water and supports wildlife.",
    supportingDetails: [
      "Rain gardens collect water.",
      "Native flowers attract bees and butterflies.",
      "The garden prevents parking lot flooding.",
    ],
    summary: "Students planted a rain garden that absorbs water and attracts pollinators with native plants.",
    vocabulary: [
      { word: "native", hint: "grows naturally in an area", definition: "originating naturally in a particular region" },
      { word: "attract", hint: "draw in", definition: "to cause to come near" },
    ],
  },
  {
    id: "g3-soccer-practice",
    grade: 3,
    title: "First Goal",
    genre: "fiction",
    text: "Jay missed an easy shot at soccer practice and felt embarrassed. His coach told him that every player misses sometimes. The next day Jay stayed after practice to take extra shots. On Saturday he scored his first goal of the season.",
    mainIdea: "Jay improves through practice after missing a shot.",
    supportingDetails: [
      "His coach said everyone misses sometimes.",
      "Jay stayed for extra shots.",
      "He scored his first goal on Saturday.",
    ],
    theme: "Practice and persistence lead to improvement.",
    summary: "After missing a shot, Jay practices extra and eventually scores his first goal.",
    vocabulary: [
      { word: "embarrassed", hint: "felt shy or ashamed", definition: "feeling self-conscious or ashamed" },
      { word: "persistence", hint: "keeping at it", definition: "continuing despite difficulty" },
    ],
  },
  {
    id: "g4-inventor",
    grade: 4,
    title: "Young Inventors Fair",
    genre: "nonfiction",
    text: "At the Young Inventors Fair, students displayed projects that solved everyday problems. One team built a cart that helps carry heavy library books. Another designed a lid that keeps soup warm longer. Judges asked each team how they tested their ideas and what they would improve next.",
    mainIdea: "Students at the inventors fair created practical solutions and explained their testing process.",
    supportingDetails: [
      "One team built a book cart.",
      "Another designed a warming soup lid.",
      "Judges asked about testing and improvements.",
    ],
    summary: "Student inventors presented useful projects and discussed testing and future improvements with judges.",
    vocabulary: [
      { word: "practical", hint: "useful in real life", definition: "designed for real use rather than theory" },
      { word: "displayed", hint: "showed publicly", definition: "put on view for others to see" },
    ],
    claim: "Student invention fairs encourage creative problem solving.",
    evidence: ["Teams solved everyday problems.", "Judges asked about testing."],
  },
  {
    id: "g4-forest-trail",
    grade: 4,
    title: "The Hidden Trail",
    genre: "fiction",
    text: "When the hiking trail closed for repairs, Elena and her dad explored an older path through the pine forest. They heard woodpeckers tapping high above and found bright orange mushrooms near a fallen log. Elena wrote everything in her nature journal, even though the trail was muddy.",
    mainIdea: "Elena and her dad explore an alternate forest trail and observe nature.",
    supportingDetails: [
      "The main trail was closed.",
      "They heard woodpeckers.",
      "Elena recorded observations in her journal.",
    ],
    theme: "Curiosity turns obstacles into discoveries.",
    summary: "With the main trail closed, Elena explores an old path and journals what she finds in the forest.",
    vocabulary: [
      { word: "explore", hint: "travel to learn about a place", definition: "to travel through an unfamiliar area to learn about it" },
      { word: "observe", hint: "watch carefully", definition: "to notice or watch carefully" },
    ],
  },
  {
    id: "g4-recycling",
    grade: 4,
    title: "Recycling Audit",
    genre: "nonfiction",
    text: "Fourth graders audited the cafeteria trash and found that many recyclable bottles were thrown away. They made signs showing which bins to use and gave a short presentation to every class. Within two weeks, the amount of recycling doubled.",
    mainIdea: "Students improved recycling by auditing trash and educating others.",
    supportingDetails: [
      "Many bottles were thrown away incorrectly.",
      "They made signs and presentations.",
      "Recycling doubled in two weeks.",
    ],
    summary: "A cafeteria audit led students to teach peers about recycling, doubling collected materials in two weeks.",
    vocabulary: [
      { word: "audited", hint: "examined carefully", definition: "conducted a systematic review" },
      { word: "recyclable", hint: "can be processed and reused", definition: "able to be processed and used again" },
    ],
    claim: "Education can quickly improve recycling habits.",
    evidence: ["Recycling doubled in two weeks.", "Students presented to every class."],
  },
  {
    id: "g5-music-lesson",
    grade: 5,
    title: "The Music Lesson",
    genre: "fiction",
    text: "Daniel wanted to quit violin after a difficult recital, but his teacher asked him to play one song he truly loved. He chose a folk tune his grandfather had been humming. As Daniel practiced the familiar melody, he remembered why music connected his family across generations.",
    mainIdea: "Daniel reconnects with music through a meaningful family song.",
    supportingDetails: [
      "He struggled after a recital.",
      "His teacher suggested one favorite song.",
      "The tune reminded him of his grandfather.",
    ],
    theme: "Music can connect families across generations.",
    summary: "After a tough recital, Daniel regains motivation by practicing a folk song linked to his grandfather.",
    vocabulary: [
      { word: "recital", hint: "a performance for an audience", definition: "a performance of music or dance" },
      { word: "generations", hint: "people born around the same time in a family", definition: "all people born and living at about the same time in a family line" },
    ],
    claim: "Personal meaning helps musicians persist through difficulty.",
    evidence: ["Daniel chose a family folk tune.", "He remembered why music mattered."],
  },
  {
    id: "g5-coral-reef",
    grade: 5,
    title: "Coral Reef Rescue",
    genre: "nonfiction",
    text: "Marine biologists are growing coral in underwater nurseries before planting it on damaged reefs. Warm ocean water and pollution have harmed many reefs worldwide. The nursery method gives young coral a safer start. Communities near the coast also reduce runoff to protect the water.",
    mainIdea: "Scientists and communities work together to restore damaged coral reefs.",
    supportingDetails: [
      "Coral is grown in nurseries first.",
      "Warm water and pollution cause harm.",
      "Communities reduce runoff.",
    ],
    summary: "Scientists grow coral in nurseries and communities cut pollution to restore damaged reefs.",
    vocabulary: [
      { word: "marine", hint: "related to the sea", definition: "related to the sea or ocean" },
      { word: "runoff", hint: "water flowing from land into rivers or sea", definition: "water from rain or land that flows into streams or oceans" },
    ],
    claim: "Reef restoration requires both science and community action.",
    evidence: ["Scientists use coral nurseries.", "Communities reduce runoff."],
  },
  {
    id: "g6-debate-team",
    grade: 6,
    title: "Join the Debate Team",
    genre: "nonfiction",
    text: "Our middle school debate team argues both sides of public issues to build critical thinking. Members research credible sources, outline claims with reasons, and respond to opposing points respectfully. Coaches say the skill transfers to essays, science projects, and everyday decisions.",
    mainIdea: "Debate team builds research skills and respectful argumentation.",
    supportingDetails: [
      "Members research credible sources.",
      "They outline claims with reasons.",
      "Skills transfer to other school work.",
    ],
    summary: "Debate teaches students to research, argue both sides, and apply critical thinking across subjects.",
    vocabulary: [
      { word: "credible", hint: "trustworthy", definition: "able to be believed; trustworthy" },
      { word: "opposing", hint: "against or different", definition: "contrary or conflicting" },
    ],
    claim: "Debate improves critical thinking across subjects.",
    evidence: ["Members research credible sources.", "Coaches say skills transfer to essays and projects."],
    theme: "The author encourages students to join debate because its skills apply beyond the team.",
  },
  {
    id: "g6-storm-night",
    grade: 6,
    title: "Storm Night",
    genre: "fiction",
    text: "During a power outage, Priya's family lit candles and told stories instead of turning on screens. Priya noticed how much calmer the house felt without constant notifications. When the lights returned, they agreed to keep one screen-free evening each week.",
    mainIdea: "A power outage leads Priya's family to value screen-free time.",
    supportingDetails: [
      "They lit candles and told stories.",
      "The house felt calmer.",
      "They planned a weekly screen-free evening.",
    ],
    theme: "Unplanned quiet time can reveal what matters most.",
    summary: "A blackout pushes Priya's family to enjoy stories together and adopt a weekly screen-free night.",
    vocabulary: [
      { word: "outage", hint: "a stoppage of service", definition: "a period when a service such as electricity is unavailable" },
      { word: "notifications", hint: "alerts from devices", definition: "messages or alerts that demand attention" },
    ],
    claim: "Less screen time can improve family calm and connection.",
    evidence: ["The house felt calmer.", "They chose a weekly screen-free evening."],
  },
  {
    id: "g7-climate-editorial",
    grade: 7,
    title: "Editorial: Urban Heat",
    genre: "nonfiction",
    text: "Cities with more pavement often become hotter than nearby suburbs, a pattern called the urban heat island effect. Planting trees and painting roofs lighter colors can lower temperatures. Critics argue these projects cost money upfront, but supporters cite lower energy bills and fewer heat-related illnesses over time.",
    mainIdea: "Urban heat islands can be reduced through trees and reflective surfaces despite upfront costs.",
    supportingDetails: [
      "Pavement makes cities hotter.",
      "Trees and light roofs help cool areas.",
      "Supporters cite long-term health and energy savings.",
    ],
    summary: "Urban heat islands result from pavement, but trees and reflective roofs offer long-term cooling benefits.",
    vocabulary: [
      { word: "urban", hint: "city-related", definition: "relating to a city" },
      { word: "upfront", hint: "at the beginning", definition: "paid or required at the start" },
    ],
    claim: "Cooling cities with trees and reflective roofs is worth the initial cost.",
    evidence: ["Trees and light roofs lower temperatures.", "Supporters cite lower energy bills and fewer illnesses."],
  },
  {
    id: "g7-museum-visit",
    grade: 7,
    title: "The Empty Frame",
    genre: "fiction",
    text: "In the museum's modern wing, a blank frame hung beside a plaque asking visitors to imagine what art might fill it. Some guests sketched ideas; others wrote poems. The curator explained that the empty frame was itself a question about who decides what belongs in a gallery.",
    mainIdea: "An empty museum frame invites visitors to question how art is chosen.",
    supportingDetails: [
      "Visitors sketched and wrote responses.",
      "The plaque asked them to imagine art.",
      "The curator said it questioned gallery choices.",
    ],
    theme: "Art can challenge us to examine rules and expectations.",
    summary: "A blank museum frame prompts visitors to reflect on who decides what counts as art.",
    vocabulary: [
      { word: "curator", hint: "person who manages a collection", definition: "a person who manages a museum collection" },
      { word: "plaque", hint: "a sign with information", definition: "a flat plate bearing an inscription" },
    ],
    claim: "Art can provoke questions about authority and inclusion.",
    evidence: ["The frame asked visitors to imagine art.", "The curator said it questioned who decides what belongs."],
  },
  {
    id: "g3-caterpillar",
    grade: 3,
    title: "From Caterpillar to Butterfly",
    genre: "nonfiction",
    text: "A caterpillar eats leaves and grows quickly. When it is ready, it forms a chrysalis and stays inside for about two weeks. Then a butterfly emerges with wet wings. The butterfly rests until its wings dry, then flies away to find flowers.",
    mainIdea: "A caterpillar transforms into a butterfly through metamorphosis.",
    supportingDetails: ["It forms a chrysalis.", "The butterfly rests until wings dry.", "It eats leaves while a caterpillar."],
    summary: "Caterpillars become butterflies by forming a chrysalis, emerging with wet wings, and resting before flying.",
    vocabulary: [
      { word: "chrysalis", hint: "a protective case during change", definition: "the hard case a caterpillar makes before becoming a butterfly" },
      { word: "emerges", hint: "comes out", definition: "comes out into view" },
    ],
  },
  {
    id: "g3-bakery",
    grade: 3,
    title: "Saturday at the Bakery",
    genre: "fiction",
    text: "Noah helped his aunt measure flour and sugar for muffins. He cracked eggs into a bowl and stirred slowly so flour would not fly everywhere. When the muffins rose in the oven, the whole shop smelled like cinnamon. Noah wrapped two muffins to bring home to his mom.",
    mainIdea: "Noah helps his aunt bake muffins at the bakery.",
    supportingDetails: ["He measured flour and sugar.", "Muffins smelled like cinnamon.", "He brought muffins home to his mom."],
    theme: "Helping others can be rewarding and fun.",
    summary: "Noah assists his aunt baking cinnamon muffins and takes some home for his mom.",
    vocabulary: [
      { word: "measure", hint: "find the right amount", definition: "to find the size, amount, or degree of something" },
      { word: "cracked", hint: "opened an egg shell", definition: "broke open without crushing completely" },
    ],
  },
  {
    id: "g4-robotics",
    grade: 4,
    title: "Robotics Club",
    genre: "nonfiction",
    text: "Our robotics club meets twice a week to design robots that complete simple tasks. Last month we programmed a robot to sort blocks by color using sensors. When the program failed, we rewrote the code in smaller steps. The coach reminded us that debugging is part of engineering.",
    mainIdea: "Robotics club teaches programming and problem solving through hands-on projects.",
    supportingDetails: ["They sort blocks by color.", "They rewrite code in smaller steps.", "Debugging is part of engineering."],
    summary: "Students in robotics club program color-sorting robots and learn to debug code patiently.",
    vocabulary: [
      { word: "programmed", hint: "gave instructions to a computer", definition: "wrote code to control a device" },
      { word: "debugging", hint: "fixing errors", definition: "finding and fixing mistakes in code" },
    ],
    claim: "Engineering requires testing and revising solutions.",
    evidence: ["They rewrote code in smaller steps.", "The coach said debugging is part of engineering."],
  },
  {
    id: "g4-time-capsule",
    grade: 4,
    title: "The Time Capsule",
    genre: "fiction",
    text: "While digging in the school garden, fourth graders uncovered a metal box buried ten years earlier. Inside were photos, a map of the old playground, and letters from students who hoped future kids would read them. The class decided to add their own letters before reburying the capsule.",
    mainIdea: "Students discover and update a school time capsule.",
    supportingDetails: ["The box was buried ten years ago.", "It contained photos and letters.", "The class added new letters."],
    theme: "Connecting past and future builds community.",
    summary: "Fourth graders find a time capsule in the garden and add their own letters before reburying it.",
    vocabulary: [
      { word: "uncovered", hint: "found by removing cover", definition: "removed covering and revealed" },
      { word: "capsule", hint: "a container holding items", definition: "a small container preserving items for the future" },
    ],
  },
  {
    id: "g5-wind-energy",
    grade: 5,
    title: "Wind Turbines on the Ridge",
    genre: "nonfiction",
    text: "Wind turbines on the coastal ridge convert moving air into electricity for nearby towns. Engineers choose locations with steady winds and minimal bird migration paths. Some residents worry about noise, while others welcome cleaner energy. Data shows the project reduced coal use in the region.",
    mainIdea: "Wind turbines provide cleaner energy but raise community questions.",
    supportingDetails: ["Engineers study wind and bird paths.", "Some residents worry about noise.", "Coal use decreased in the region."],
    summary: "Coastal wind turbines cut coal use while communities debate noise and placement.",
    vocabulary: [
      { word: "convert", hint: "change from one form to another", definition: "to change something into a different form" },
      { word: "migration", hint: "seasonal movement of animals", definition: "movement from one region to another and back" },
    ],
    claim: "Wind energy can reduce fossil fuel use.",
    evidence: ["Turbines convert wind to electricity.", "Coal use decreased in the region."],
  },
  {
    id: "g5-journal",
    grade: 5,
    title: "The Hidden Journal",
    genre: "fiction",
    text: "While cleaning the attic, Rosa found her grandmother's journal from childhood. Entries described a drought that forced the family to share water with neighbors. Rosa realized her grandmother's generosity started long before Rosa knew her. She began her own journal that same evening.",
    mainIdea: "Rosa learns about her grandmother's past through a journal.",
    supportingDetails: ["The journal described a drought.", "The family shared water with neighbors.", "Rosa started her own journal."],
    theme: "Family history can inspire present choices.",
    summary: "Rosa discovers her grandmother's drought-era journal and starts writing her own.",
    vocabulary: [
      { word: "drought", hint: "a long period with little rain", definition: "a prolonged shortage of rain" },
      { word: "generosity", hint: "willingness to give", definition: "the quality of being willing to give or share" },
    ],
  },
  {
    id: "g6-microplastics",
    grade: 6,
    title: "Microplastics in Rivers",
    genre: "nonfiction",
    text: "Scientists sampled river water upstream and downstream of a city and found more microplastic fibers downstream. Many fibers likely come from synthetic clothing washed in homes. Filters on washing machines could capture some particles before they reach waterways. Public education campaigns also reduce litter that breaks into smaller pieces.",
    mainIdea: "Microplastic pollution increases downstream and requires multiple solutions.",
    supportingDetails: ["More fibers were found downstream.", "Synthetic clothing is a likely source.", "Filters and education can help."],
    summary: "River studies link microplastics to urban areas and suggest filters plus public education.",
    vocabulary: [
      { word: "synthetic", hint: "human-made", definition: "made by chemical synthesis rather than found in nature" },
      { word: "particles", hint: "tiny pieces", definition: "very small pieces of matter" },
    ],
    claim: "Reducing microplastics requires technology and behavior change.",
    evidence: ["Filters could capture particles.", "Education campaigns reduce litter."],
    theme: "City-related activity likely adds microplastics to rivers downstream.",
  },
  {
    id: "g6-coding-mentor",
    grade: 6,
    title: "The Coding Mentor",
    genre: "fiction",
    text: "When Aisha struggled with her first Python project, a high school mentor paired with her online each Thursday. Instead of giving answers, the mentor asked questions that helped Aisha find bugs herself. By the science fair, Aisha's temperature sensor project worked reliably.",
    mainIdea: "A mentor helps Aisha solve coding problems by guiding her thinking.",
    supportingDetails: ["They met online on Thursdays.", "The mentor asked questions instead of giving answers.", "Her sensor project worked at the fair."],
    theme: "Good mentors build independence, not dependence.",
    summary: "Aisha's mentor uses questions to help her debug code until her science fair project succeeds.",
    vocabulary: [
      { word: "reliably", hint: "in a dependable way", definition: "in a way that can be trusted to work" },
      { word: "paired", hint: "matched as partners", definition: "joined together as a team" },
    ],
  },
  {
    id: "g7-ai-editorial",
    grade: 7,
    title: "Editorial: AI in Classrooms",
    genre: "nonfiction",
    text: "Some districts pilot AI tutors that adapt practice problems to each student. Supporters argue instant feedback saves teacher time for deeper discussions. Critics worry students may accept AI explanations without verifying facts. A balanced policy might require students to cite sources and explain reasoning in their own words.",
    mainIdea: "AI tutors offer benefits but require policies that protect critical thinking.",
    supportingDetails: ["AI adapts practice to each student.", "Critics fear unverified explanations.", "Policies could require citing sources."],
    summary: "AI tutoring may help practice but needs rules so students still think critically and cite sources.",
    vocabulary: [
      { word: "pilot", hint: "test on a small scale", definition: "to test a program before wider use" },
      { word: "verify", hint: "check if true", definition: "to confirm the accuracy or truth of something" },
    ],
    claim: "Schools should adopt AI tools with safeguards for critical thinking.",
    evidence: ["Supporters cite instant feedback.", "Critics worry about unverified explanations.", "Policies could require citing sources."],
  },
];

export function passagesForGrade(grade: number): Passage[] {
  return PASSAGES.filter((p) => p.grade <= grade && p.grade >= grade - 1);
}
