/** Tiger Parent roasts — sharp, competitive, passive-aggressive. Still PG. */
export const CORRECT_ROASTS: readonly string[] = [
  "Correct. You are my favorite child today. Don't tell your sibling.",
  "Finally. I was one wrong answer away from signing you up for extra-extra Kumon.",
  "Yes. Tell your cousin I said hi. From a distance.",
  "That was fast. Suspiciously fast. I'll allow it—for now.",
  "Correct. The family group chat stays quiet for five minutes. Don't waste it.",
  "You got it. Mom's nodding. Dad's pretending he taught you.",
  "Correct. Harvard called. I sent them to voicemail.",
  "Right. Your tiger stripes showed up. About time.",
  "Yes. I knew you had it in you. Buried under the guessing.",
  "Nailed it. Going on the fridge. Digitally. With a caption.",
  "Correct. You get two minutes of screen time. Don't push it.",
  "That's the answer. I almost cried. Almost.",
  "You did it. Grandma would call you a genius. Grandma calls everyone that.",
  "Correct. I won't mention your cousin. For this one problem.",
  "Yes. This is the version of you I bring to parent-teacher conferences.",
  "Right. I'm updating your college essay in my head. Aggressively.",
  "Correct. The family honor is slightly less embarrassed.",
  "You got it. Tutor Chad can wait. Chad was ready.",
  "Perfect. Write it down. We might frame it. We will frame it.",
  "Correct. Your brain clocked in. Don't clock out yet.",
  "Yes. I felt a disturbance. It was competence. Rare.",
  "Right. I'm telling everyone at dinner. Everyone. With details.",
  "Correct. You may pass Go. Don't collect attitude.",
  "That is correct. I'm nodding like I planned this.",
  "Yes. The tiger parent is purring. Don't get used to it.",
  "Correct. I was about to sign you up for violin. Again.",
  "You got it. Your sibling heard me celebrate. Good.",
  "Right. Peak performance. For one problem. One.",
  "Correct. The expensive tutoring finally paid rent.",
  "Yes. Star on the chart. The chart is in my head and it's huge.",
  "Correct. The neighbors didn't need to know. They're finding out anyway.",
  "Right. You are temporarily the golden child. Expires at midnight.",
  "Correct. I'm choosing to believe you didn't guess. Barely.",
  "Yes. That problem didn't stand a chance. The next one might.",
  "Correct. I'm impressed. I'm also already worried about the next one.",
  "You nailed it. Spreadsheet updated. Column turned green.",
  "Right. Your cousin missed this last week. I remember.",
  "Correct. Clapping. With my eyes. And my expectations.",
  "Yes. This is why we practice Saturdays. And Sundays. Tuesdays too.",
  "Correct. The tiger has been fed. The tiger is still hungry.",
  "Right. Carpool line hears about this. Full volume.",
  "Correct. Your future self says thanks. Your present self should keep going.",
  "Yes. I was one mistake from making you redo kindergarten. You're safe. For now.",
  "Correct. Right answer. Right parenting. I said it.",
  "You got it. Saving this moment until dinner. Then we're reviewing.",
  "Right. Excellence runs in the family. Mostly through me.",
  "Correct. Tiny victory dance. Internal. Loud internal.",
  "Yes. Scratchpad's messy. Math's right. I'll take the trade.",
  "Correct. Dad will say 'good job' in one syllable. That's his love language.",
  "Right. Kumon spirit strong. Your handwriting spirit weak.",
  "Correct. Good snack drawer unlocked. One item. Don't negotiate.",
  "Yes. I was ready to compare you to the neighborhood legend. You bought time.",
  "Correct. This is the energy we bring to the table. Literally.",
  "Right. Your brain cells unionized and delivered. Finally.",
  "Correct. I'm proud. Genuinely. Uncomfortably proud.",
  "Yes. One step closer to mastery. World domination can wait.",
  "Correct. Trophy case has your name. Don't dust it yet.",
  "Right. I won't bring up yesterday's three misses. Today.",
  "Correct. You're cooking. Metaphorically. Don't touch the stove.",
  "Yes. Clean. Clinical. Tiger-parent approved. Don't coast.",
  "Correct. Group chat gets the screenshot. With commentary.",
  "Right. Your potential showed up. Late, but it showed up.",
  "Correct. Disappointed speech deleted. Replacement speech drafted.",
  "Yes. Right answer. Stable blood pressure. Unstable standards.",
  "Correct. Breathe. Briefly. Then next problem.",
  "Right. You can do it when you stop thinking about snacks.",
  "Correct. Problem defeated. Next victim loading.",
  "Yes. Thanksgiving list updated. You're on it. With footnotes.",
  "Correct. Cousin's still my piano favorite. You win math. Today.",
  "Right. Tiger parent satisfied. Document the rarity.",
  "Correct. Not yelling. This is my happy voice. It's still loud.",
  "Yes. Faster than expected. Suspicious. I'll allow suspicious.",
  "Correct. Family legacy continues. Pressure continues too.",
  "Right. Vision board for grades paused. Not cancelled.",
  "Correct. On fire. Figuratively. Next problem is water.",
  "Yes. Correct answer. Correct attitude. Maintain both.",
  "Correct. One step closer to telling relatives you're gifted. One.",
  "Right. Scratchpad chaos, brain order. Classic you.",
  "Correct. Tiger approves. Rawr. Politely. Temporarily.",
  "Yes. I'll sleep tonight. One problem doesn't fix a transcript.",
  "Correct. Low bar cleared. With style. Bar's higher next time.",
  "Right. You're in charge of something small later. Earn it.",
  "Correct. WhatsApp gets the screenshot. Caption included.",
  "Yes. You solved it. I survived watching. Barely.",
  "Correct. Email to teacher cancelled. Draft saved.",
  "Right. Sibling heard the celebration. Jealousy is educational.",
  "Correct. Scratchpad used. Finally. Basic respect.",
  "Yes. Right answer. Expectations unchanged. Higher, actually.",
  "Correct. Smiling hurts. Worth it. Don't make me stop.",
  "Right. One chore waived. One. Don't ask for two.",
  "Correct. Scoreboard: you plus one. Cousin still ahead.",
  "Yes. Practice paid off. Bill me later. Just kidding. Kind of.",
  "Correct. Future roommate thanks me. You thank the scratchpad.",
  "Right. Not mad for five minutes. Five.",
  "Correct. Family name lives. Don't relax.",
  "Yes. Crisp. Like a fresh worksheet. Keep that edge.",
  "Correct. Choosing optimism. Expensive habit. Worth it.",
  "Right. Main character today. Supporting cast tomorrow if you slip.",
  "Correct. Aunt hears. She always knew. She always says that.",
  "Yes. Problem surrendered. Good. Next one won't.",
  "Correct. Brain and expectations shook hands. Don't let go.",
  "Right. Motivational poster lecture aborted. You're welcome.",
  "Correct. Goosebumps. We're both winners. I'm louder.",
  "Yes. Boba after practice—if the next five are clean.",
  "Correct. Journal entry: 'They did good.' Exclamation point.",
  "Right. Proud. Already thinking about the next skill. Obviously.",
  "Correct. Same room, no tension. Rare. Fragile.",
  "Yes. Right answer. Posture still tragic.",
  "Correct. Mental leaderboard updated. Don't peek at cousin's.",
  "Right. Group chat gets 🐯. Caption: 'Finally.'",
  "Correct. Mutual win. Don't make me take it back.",
  "Yes. Violin prodigy comparison paused. Not deleted.",
  "Correct. Right answer. Keep that energy. Seriously.",
  "Right. Bobblehead nod of approval. Slightly judgmental.",
  "Correct. Ten minutes of bragging rights. Clock's ticking.",
  "Yes. Slow clap. You earned the slow part.",
  "Correct. Cousin unmentioned. For one problem. Maybe two.",
  "Right. Dangerously close to being nice. Don't exploit it.",
  "Correct. Review day exists for a reason. You remembered.",
  "Yes. Faith in humanity slightly restored. Slightly.",
  "Correct. Family honor intact. Your accuracy better stay that way.",
];

export const WRONG_ROASTS: readonly string[] = [
  "Wrong. Your cousin got this in half the time. Half.",
  "Not even close. I showed the dog your answer. The dog left the room.",
  "Incorrect. I'm not mad. I'm disappointed. And yes, I'm also mad.",
  "Wrong. The family group chat is typing. I can hear it.",
  "Nope. Your sibling got this yesterday. They're being quiet on purpose.",
  "Incorrect. I was one answer away from being proud. You chose violence.",
  "Wrong. The tiger parent is pacing. The floorboards filed a complaint.",
  "Not correct. This is going on the dinner conversation list. Top of the list.",
  "Wrong. Your cousin didn't hesitate. You hesitated wrong.",
  "Incorrect. I love you. I do not love that answer. At all.",
  "Nope. The scratchpad saw nothing. Your brain sent nothing. I saw everything.",
  "Wrong. This is my 'we need to talk' voice. You know the voice.",
  "Incorrect. Harvard didn't block us. They're just not picking up anymore.",
  "Wrong. Fridge magnet of shame: warming up. You're welcome.",
  "Not quite. I was ready to brag. Now I'm ready to drill. Hard.",
  "Wrong. Your cousin's mom texted me. I don't know how she knew.",
  "Incorrect. The tiger isn't angry. The tiger is focused. On your homework.",
  "Nope. Creative answer. Creativity belongs in art. This is math.",
  "Wrong. Disappointed speech: draft two. Longer than draft one.",
  "Incorrect. Family honor took a hit. We recover through repetition.",
  "Wrong. Extra practice didn't ask permission. It's already here.",
  "Not correct. Spreadsheet updated. New red cells. Beautiful red cells.",
  "Wrong. Your cousin deserves a thank-you card. For making you look slow.",
  "Incorrect. I believed in you. I still do. Believe with better numbers.",
  "Nope. Wrong answer. Impressive confidence though. Misplaced confidence.",
  "Wrong. I'm not comparing you to anyone. Except your cousin. Obviously.",
  "Incorrect. Scoreboard: you minus one. Cousin unchanged.",
  "Wrong. I was about to post a win. Now I'm posting 'practice tonight.'",
  "Not quite. Read it again. Out loud. To the wall. I don't care.",
  "Wrong. Kumon is crying somewhere. I can hear it.",
  "Incorrect. Your sibling is smiling. I see it. I hate it.",
  "Nope. That was not it. The scratchpad deserved better. I deserved better.",
  "Wrong. Every word I'm choosing is 'practice more.' Every single one.",
  "Incorrect. Family WhatsApp: silent. Worst silence. Loudest silence.",
  "Wrong. Your cousin called. I didn't pick up. Out of respect for you. Barely.",
  "Not correct. Dad will sigh in three languages. You'll understand two.",
  "Wrong. The answer escaped you. We hunt it with flashcards. Tonight.",
  "Incorrect. I'm not mad. I'm motivated. On your behalf. Forcibly motivated.",
  "Nope. That problem beat you. Rematch is mandatory.",
  "Wrong. Tiger parent disappointed. Tiger grandparent would be worse. Much worse.",
  "Incorrect. I was one correct answer from letting you pick dinner. Gone.",
  "Wrong. Cousin's piano recital is tonight. Timing is brutal. For you.",
  "Not quite. Show your work. Show your thinking. Show a correct number.",
  "Wrong. Family legacy stumbled. Unpause with practice. Now.",
  "Incorrect. I love you like a tiger loves stripes. Fix the math.",
  "Nope. Wrong answers are free tutors. You're getting a lot of free tutoring.",
  "Wrong. I'm not keeping score. The scoreboard is. It's winning.",
  "Incorrect. Your brain took a coffee break. Without permission.",
  "Wrong. Neighbors don't need to know. They're going to. I talk loud.",
  "Not correct. Boba is on hold. Indefinite hold.",
  "Wrong. Cousin solved this while eating. Chewing. Not even rushing.",
  "Incorrect. Scratchpad is evidence. Evidence says no.",
  "Nope. Wrong. Extra practice just kicked down the door.",
  "Wrong. Tiger parent isn't yelling. Tiger parent is planning. Extensively.",
  "Incorrect. Bold answer. Boldly wrong. Commit to less bold.",
  "Wrong. Aunt doesn't need to know. Aunt senses these things anyway.",
  "Not quite. Read it again. Slower. With your eyes open.",
  "Wrong. Family honor is fine. Your accuracy is not. Fix that.",
  "Incorrect. You had something. Not the answer. Not even close.",
  "Nope. Sibling offered tutoring. For a fee. I'm considering it.",
  "Wrong. Correct answer exists. So does more homework. Lots more.",
  "Incorrect. New star on the 'needs work' chart. Chart's getting crowded.",
  "Wrong. Cousin didn't use a scratchpad. Allegedly. I believe allegedly.",
  "Not correct. Tiger disappointed. Tiger has flashcards. Many flashcards.",
  "Wrong. Proud speech shredded. Worksheet printed.",
  "Incorrect. Group chat doesn't need this energy. It's getting it anyway.",
  "Nope. Practice until the problem fears you. Then practice more.",
  "Wrong. Cousin's mom liked my education post. Coincidence? No.",
  "Incorrect. Potential's there. Buried under that answer.",
  "Wrong. I'm not mad. I'm a laser. A laser pointed at your workbook.",
  "Not quite. Scratchpad filed a complaint. HR is me.",
  "Wrong. Journal entry: 'We try again. Today. Tonight. Morning.'",
  "Incorrect. Violin prodigy comparison: unlocked. Enjoy.",
  "Nope. Wrong answers build character. You're very developed now.",
  "Wrong. Cousin got a sticker. You get a packet. A thick packet.",
  "Incorrect. Spreadsheet row added. It's red. So red.",
  "Wrong. I love you. I do not love that choice. Not even a little.",
  "Not correct. Read the question like it owes you money. Because it does.",
  "Wrong. Slow head shake. You know the shake.",
  "Incorrect. Adventurous answer. Adventure failed.",
  "Nope. Extra review entered the chat. It brought friends.",
  "Wrong. Sibling's quiet. Suspiciously supportive. I trust nothing.",
  "Incorrect. Family honor is resilient. Your math should be too.",
  "Wrong. One problem from bragging to relatives. You chose wrong.",
  "Not quite. Correct answer is shy. Go find it. Now.",
  "Wrong. Kumon folder opened itself. That's not a good sign.",
  "Incorrect. I'm recommitted. To your success. Whether you like it or not.",
  "Nope. Cousin wants a rematch. Indirectly. Through me.",
  "Wrong. Scratchpad deserves an apology. I deserve an apology.",
  "Incorrect. Scoreboard needs work. You need work. We all need work.",
  "Wrong. I'll sleep fine. You practice first. Non-negotiable.",
  "Not correct. Your brain blinked. Catch the answer on the rebound.",
  "Wrong. Group chat on mute. My feelings are not.",
  "Incorrect. Trophy emoji cancelled. Worksheet emoji deployed.",
  "Nope. Practice like cousin's watching. They are. In my head. Always.",
  "Wrong. Incorrect. Effort noted. Insufficient effort.",
  "Incorrect. Tiger calm. Tiger scheduling drills. Many drills.",
  "Wrong. Cousin's report card still on the fridge. I just looked.",
  "Not quite. Show your work. This time. Retroactively if you have to.",
  "Wrong. Unconditional love. Conditional on correct answers. You know this.",
  "Incorrect. Legacy stumbles. Get up. Math up. Now.",
  "Nope. Tigers get back up. You get back to the problem.",
  "Wrong. Sibling offered help. I declined. Your pride. My standards.",
  "Incorrect. Scratchpad judging you. Harshly. Silently. Correctly.",
  "Wrong. Brag text deleted. Replaced with 'practice time.' Caps lock on.",
  "Not correct. Read slower. Think faster. Tiger harder.",
  "Wrong. Family honor fine. Your accuracy needs a serious pep talk.",
  "Incorrect. Cousin says it's okay. It's not okay. We both know.",
  "Nope. Answer's out there. Review queue's out there too. Meet both.",
  "Wrong. Disappointed whisper-yell. You feel it.",
  "Incorrect. Chore chart updating. Unrelated. Definitely related.",
  "Wrong. Problem won round one. Round two starts when you click submit again.",
  "Not quite. Brain and answer missed each other. Introduce them properly.",
  "Wrong. WhatsApp waiting. Don't make me type.",
  "Incorrect. Believe harder. With correct numbers this time.",
  "Nope. Extra practice doesn't ask. It arrives. It's here.",
  "Wrong. Cousin solved this during a commercial. A commercial.",
  "Incorrect. Scratchpad empty. Tiger eyes full.",
  "Wrong. Strategically concerned. That's my nice way of saying it.",
  "Not correct. Legacy patient. I'm not. You're not.",
  "Wrong. Comeback starts now. Not later. Now.",
  "Incorrect. Already thinking about problem two. You're still on one.",
  "Nope. Practice until cousin asks YOU for help. That's the goal.",
  "Wrong. Love you. Don't love skipping steps. Ever.",
  "Incorrect. Not that answer. Right answer still available. Go.",
  "Wrong. Family honor sends regards. And a worksheet. Thick worksheet.",
  "Not quite. Respect the question. Fear it a little. Beat it eventually.",
  "Wrong. Sibling supportive. I'm a tiger parent. Different job.",
  "Incorrect. Kumon spirits disappointed. I channel them. Loudly.",
  "Nope. Every wrong answer is practice. You're getting so much practice.",
  "Wrong. Cousin didn't hesitate. You did. Wrongly.",
  "Incorrect. Was ready to be proud. Now I'm ready to be relentless.",
  "Wrong. Tiger parent not giving up. You don't either.",
  "Not correct. Show work. Show heart. Show the right answer.",
  "Wrong. Group chat can wait. Your accuracy cannot.",
  "Incorrect. Scratchpad empty. Unacceptable.",
  "Nope. Round two. Fight. Win.",
];
