/** Tiger Parent praise — warm, competitive, slightly unhinged. */
export const CORRECT_ROASTS: readonly string[] = [
  "Correct. You are my favorite child today. Don't tell your sibling.",
  "Finally. I was one wrong answer away from enrolling you in extra extra Kumon.",
  "Yes! Tell your cousin I said hi. From a distance.",
  "That was fast. Suspiciously fast. I'll allow it.",
  "Correct. The family group chat can stay peaceful for five minutes.",
  "You got it! Mom is doing that little proud nod. Dad is pretending he taught you.",
  "Beautiful. Harvard called. I sent them to voicemail.",
  "Correct! Your tiger stripes are showing.",
  "Yes! I knew you had it in you. Deep, deep down.",
  "Nailed it. I'm putting this on the fridge. Digitally.",
  "Correct. You may have one (1) minute of screen time. Just kidding. Two minutes.",
  "That's the answer! I almost cried. Almost.",
  "You did it! Grandma would say you're a genius. Grandma says that about everyone though.",
  "Correct. I won't compare you to your cousin. For this one problem.",
  "Yes! This is the version of you I show at parent-teacher conferences.",
  "Right! I'm updating your future college essay in my head.",
  "Correct. The family honor is slightly restored.",
  "You got it! I was ready to hire a tutor named Chad. Chad can wait.",
  "Perfect. Write that down. We might frame it.",
  "Correct! Your brain woke up. Welcome back.",
  "Yes! I felt a disturbance in the Force. It was competence.",
  "Right answer! I'm telling everyone at dinner. Everyone.",
  "Correct. You may pass Go. You may collect $200 in emotional support.",
  "That is correct. I am nodding aggressively.",
  "Yes! The tiger parent within me is purring.",
  "Correct. I was about to sign you up for violin lessons. Again.",
  "You got it! Your sibling is shaking right now.",
  "Right! This is peak performance. Peak.",
  "Correct. I knew the expensive tutoring would work eventually.",
  "Yes! Put a star on your chart. The chart is in my heart.",
  "Correct. The neighbors don't need to hear about this. I will tell them anyway.",
  "Right answer! You are temporarily the golden child.",
  "Correct. I am choosing to believe you didn't guess.",
  "Yes! That problem didn't stand a chance against our household work ethic.",
  "Correct. I'm not mad. I'm impressed. I'm both.",
  "You nailed it! The family spreadsheet is updated.",
  "Right! Your cousin got this wrong last week. Not that I'm keeping track.",
  "Correct. I am clapping. With my eyes.",
  "Yes! This is why we practice on Saturdays. And Sundays. And Tuesdays.",
  "Correct. The tiger has been fed. For now.",
  "Right! I will brag about this in the carpool line.",
  "Correct. Your future self says thank you.",
  "Yes! I was one mistake away from making you redo kindergarten.",
  "Correct. The answer is right and so is my parenting.",
  "You got it! I'm saving this moment in my memory forever. Or until dinner.",
  "Right answer! Excellence runs in the family. Mostly on my side.",
  "Correct. I am doing a tiny victory dance. Internally.",
  "Yes! Your handwriting on the scratchpad still needs work but the math is fine.",
  "Correct. I will tell your dad. He will say 'good job' in one syllable.",
  "Right! The Kumon spirit is strong in this one.",
  "Correct. You earned the good snack drawer tonight.",
  "Yes! I was ready to compare you to a neighborhood legend. You saved yourself.",
  "Correct. This is the energy we bring to the dining table.",
  "Right! Your brain cells formed a union and they delivered.",
  "Correct. I am proud. Genuinely. Scary, right?",
  "Yes! One step closer to world domination. I mean, grade level mastery.",
  "Correct. The family trophy case has a spot with your name on it.",
  "Right answer! I will not bring up the three you missed yesterday.",
  "Correct. You are cooking. Metaphorically. Please don't cook unsupervised.",
  "Yes! That was clean. Clinical. Tiger-parent approved.",
  "Correct. I am texting the good news. The group chat will explode.",
  "Right! Your potential is showing. About time.",
  "Correct. I was composing a disappointed speech. Deleted.",
  "Yes! The answer is correct and my blood pressure is stable.",
  "Correct. You may breathe. Briefly.",
  "Right! I knew you could do it when you stop daydreaming about snacks.",
  "Correct. This problem has been defeated. On to the next victim.",
  "Yes! I'm adding this to the list of things to mention at Thanksgiving.",
  "Correct. Your cousin is still my favorite for piano. You win math today.",
  "Right answer! The tiger parent is satisfied. Rare event.",
  "Correct. I am not yelling. This is my happy voice.",
  "Yes! You got it faster than I expected. Suspicious. But I'll take it.",
  "Correct. The family legacy continues. No pressure.",
  "Right! I was about to make a vision board for your grades. Paused.",
  "Correct. You are on fire. Figuratively. Fire safety still matters.",
  "Yes! That is the correct answer and also the correct attitude.",
  "Correct. I am one step closer to telling relatives you are gifted.",
  "Right! Your scratchpad work was messy but your brain was tidy.",
  "Correct. The tiger approves. Rawr. Politely.",
  "Yes! I will sleep well tonight. One problem at a time.",
  "Correct. You didn't disappoint. Low bar cleared with style.",
  "Right answer! I'm putting you in charge of something small later.",
  "Correct. The family WhatsApp is getting a screenshot.",
  "Yes! You solved it. I solved dinner stress. Teamwork.",
  "Correct. I was ready to email the teacher. Cancelled.",
  "Right! Your sibling heard me celebrate. Jealousy is fuel.",
  "Correct. This is what happens when you don't skip the scratchpad.",
  "Yes! The answer is right. My expectations remain high.",
  "Correct. I am smiling. It hurts my face. Worth it.",
  "Right answer! You are temporarily exempt from one chore. One.",
  "Correct. The tiger parent scoreboard: you plus one.",
  "Yes! I knew those practice problems would pay off. Eventually.",
  "Correct. Your future college roommate will thank me for this.",
  "Right! I am not mad at you for the last five minutes.",
  "Correct. The family name lives another day.",
  "Yes! That was crisp. Like a fresh worksheet.",
  "Correct. I am choosing optimism. Don't ruin it.",
  "Right answer! You are the main character today.",
  "Correct. I will tell your aunt. She will say she always knew.",
  "Yes! The problem surrendered. Good.",
  "Correct. Your brain and my expectations shook hands.",
  "Right! I was one wrong answer from a motivational poster lecture.",
  "Correct. You got it. I got goosebumps. We're both winners.",
  "Yes! This is the version of you that gets boba after practice.",
  "Correct. The tiger parent journal entry: 'They did good today.'",
  "Right answer! I am proud and also already thinking about the next skill.",
  "Correct. You may exist in the same room as me without tension.",
  "Yes! That answer was correct. Your posture should still improve.",
  "Correct. I am updating the mental leaderboard. You're climbing.",
  "Right! The family group chat emoji reaction: 🐯",
  "Correct. You solved it. I survived watching. Mutual win.",
  "Yes! I was about to compare you to a violin prodigy. You're safe.",
  "Correct. The answer is right. Keep that energy.",
  "Right answer! I am nodding like a bobblehead of approval.",
  "Correct. You earned bragging rights for the next ten minutes.",
  "Yes! The tiger parent within me is doing a slow clap.",
  "Correct. I will not mention your cousin. For the next problem. Maybe.",
  "Right! You got it. I am dangerously close to being nice.",
  "Correct. This is why we don't skip review day.",
  "Yes! Your answer is correct. My faith in humanity: slightly restored.",
  "Correct. The family honor is intact. For now. Stay vigilant.",
];

export const WRONG_ROASTS: readonly string[] = [
  "Wrong. Your cousin would've gotten that in half the time. Half.",
  "Not quite. I showed this to the dog. The dog looked concerned.",
  "Incorrect. I'm not mad. I'm just disappointed. And mad.",
  "Wrong answer. The family group chat is typing…",
  "Nope. Your sibling got this one right yesterday. Just saying.",
  "Incorrect. I was one answer away from being proud. So close. So far.",
  "Wrong. The tiger parent is pacing. The floor is suffering.",
  "Not correct. I'm adding this to the mental list for dinner conversation.",
  "Wrong. Your cousin didn't even hesitate on this one.",
  "Incorrect. I love you. I do not love that answer.",
  "Nope. The scratchpad saw nothing useful. Neither did I.",
  "Wrong. I'm not yelling. This is my 'we need to talk' voice.",
  "Incorrect. Harvard just blocked our number.",
  "Wrong answer. The fridge magnet of shame is warming up.",
  "Not quite. I was ready to brag. Now I'm ready to drill.",
  "Wrong. Your cousin's mom already texted me. I don't know how.",
  "Incorrect. The tiger is not angry. The tiger is focused. On you.",
  "Nope. That answer was creative. Creativity belongs in art class.",
  "Wrong. I'm composing a disappointed speech. Draft one complete.",
  "Incorrect. The family honor took a tiny hit. We will recover.",
  "Wrong answer. Extra practice just winked at you.",
  "Not correct. I am updating the spreadsheet. The red cells multiply.",
  "Wrong. Your cousin would like a thank-you card for making them look good.",
  "Incorrect. I believed in you. I still do. Believe harder.",
  "Nope. The answer was wrong but your confidence was impressive.",
  "Wrong. I'm not comparing you to anyone. Except your cousin. Briefly.",
  "Incorrect. The tiger parent scoreboard: you minus one.",
  "Wrong answer. I was about to post a win. Now I'm posting nothing.",
  "Not quite. Read the question again. Then again. Then ask yourself why.",
  "Wrong. The Kumon spirit is weeping somewhere.",
  "Incorrect. Your sibling is trying not to smile. I see you.",
  "Nope. That was not it. The scratchpad deserved better.",
  "Wrong. I am choosing my words carefully. They are all 'practice more'.",
  "Incorrect. The family WhatsApp is silent. The worst silence.",
  "Wrong answer. Your cousin called. I didn't pick up. Out of respect for you.",
  "Not correct. I will tell your dad. He will sigh in three languages.",
  "Wrong. The answer escaped you. We will hunt it down with flashcards.",
  "Incorrect. I am not mad. I am motivated. On your behalf. Forcibly.",
  "Nope. That problem beat you. Rematch incoming.",
  "Wrong. The tiger parent is disappointed. The tiger grandparent would be worse.",
  "Incorrect. I was one correct answer away from letting you pick dinner.",
  "Wrong answer. Your cousin's piano recital is tonight. This timing is awkward.",
  "Not quite. Show your work. Show your thinking. Show remorse.",
  "Wrong. The family legacy paused for a moment. Unpause with practice.",
  "Incorrect. I love you like a tiger loves stripes. Fix the answer.",
  "Nope. That was wrong. The good news: wrong answers are free tutors.",
  "Wrong. I'm not keeping score. The scoreboard is keeping score.",
  "Incorrect. Your brain took a coffee break. Wake it up.",
  "Wrong answer. The neighbors don't need to know. They will find out.",
  "Not correct. I was ready to give you boba. The boba is on hold.",
  "Wrong. Your cousin solved this while eating a snack. Think about that.",
  "Incorrect. The scratchpad is evidence. The evidence is not favorable.",
  "Nope. Wrong. I'm already mentally scheduling more practice.",
  "Wrong. The tiger parent is not yelling. The tiger parent is planning.",
  "Incorrect. That answer was bold. Boldly incorrect.",
  "Wrong answer. I will not tell your aunt. Your aunt can sense these things.",
  "Not quite. Read it again. Out loud. To the wall. Whatever works.",
  "Wrong. The family honor is fine. Your accuracy is not.",
  "Incorrect. I believed you had it. You had something. Not the answer.",
  "Nope. Your sibling would like you to know they are available for tutoring. For a fee.",
  "Wrong. The correct answer is out there. So is more homework.",
  "Incorrect. I'm adding a star to the 'needs work' chart. The chart is large.",
  "Wrong answer. Your cousin didn't even use a scratchpad. Allegedly.",
  "Not correct. The tiger is disappointed. The tiger also has flashcards ready.",
  "Wrong. I was composing a proud speech. Shredded.",
  "Incorrect. The family group chat doesn't need this energy.",
  "Nope. That was wrong. Practice until the problem fears you.",
  "Wrong. Your cousin's mom just liked my post about education. Coincidence?",
  "Incorrect. The answer was wrong. Your potential is still there. Buried slightly.",
  "Wrong answer. I am not mad. I am focused. Like a laser. On math.",
  "Not quite. The scratchpad saw that and filed a complaint.",
  "Wrong. The tiger parent journal entry: 'We try again tomorrow. And today.'",
  "Incorrect. I will not compare you to violin prodigies. Today I will.",
  "Nope. Wrong. The good news is wrong answers build character. So much character.",
  "Wrong. Your cousin got a sticker for this skill. You get a worksheet.",
  "Incorrect. The family spreadsheet has a new row. It's red.",
  "Wrong answer. I love you. I do not love that choice.",
  "Not correct. Read the question like it owes you money.",
  "Wrong. The tiger parent is doing that slow head shake.",
  "Incorrect. That answer was adventurous. Adventure belongs elsewhere.",
  "Nope. Wrong. Extra review just entered the chat.",
  "Wrong. Your sibling is being very quiet. Suspiciously supportive.",
  "Incorrect. The family honor is resilient. Your accuracy should match.",
  "Wrong answer. I was one problem away from bragging to relatives.",
  "Not quite. The correct answer is shy. Go find it.",
  "Wrong. The Kumon folder just opened itself. Spooky.",
  "Incorrect. I am not disappointed. I am… recommitted. To your success.",
  "Nope. That was wrong. Your cousin would like a rematch. Indirectly.",
  "Wrong. The scratchpad deserves an apology.",
  "Incorrect. The tiger parent scoreboard needs work. You need work. We all need work.",
  "Wrong answer. I will sleep fine. You should practice first.",
  "Not correct. Your brain blinked. Catch the answer on the rebound.",
  "Wrong. The family group chat is on mute. My feelings are not.",
  "Incorrect. I was ready to post a trophy emoji. Now I post a worksheet emoji.",
  "Nope. Wrong. Practice like your cousin is watching. They are. In my head.",
  "Wrong. The answer was incorrect. The effort was noted. Insufficiently.",
  "Incorrect. The tiger is calm. The tiger is also scheduling drills.",
  "Wrong answer. Your cousin's report card is still on the fridge. Just noticed.",
  "Not quite. Show your work next time. Show it this time retroactively if possible.",
  "Wrong. I love you unconditionally. I love correct answers conditionally.",
  "Incorrect. The family legacy stumbles but does not fall. Get up. Math up.",
  "Nope. That answer was wrong. The good news: tigers always get back up.",
  "Wrong. Your sibling offered to help. I declined. Out of pride. Yours.",
  "Incorrect. The scratchpad is judging you. Silently. Harshly.",
  "Wrong answer. I was composing a brag text. Deleted. Replaced with 'practice time'.",
  "Not correct. Read slower. Think faster. Tiger harder.",
  "Wrong. The family honor is fine. Your accuracy needs a pep talk.",
  "Incorrect. Your cousin would like you to know it's okay. It's not okay.",
  "Nope. Wrong. The answer is out there. So is the review queue.",
  "Wrong. I am not yelling. This is my disappointed whisper-yell.",
  "Incorrect. The tiger parent is updating the chore chart. Unrelated. Maybe.",
  "Wrong answer. That problem won round one. Round two is now.",
  "Not quite. Your brain and the answer missed each other. Introduce them.",
  "Wrong. The family WhatsApp is waiting. Don't make me post.",
  "Incorrect. I believed in you. I still do. Believe with better math.",
  "Nope. Wrong. Extra practice doesn't ask. It arrives.",
  "Wrong. Your cousin solved this during a commercial break.",
  "Incorrect. The scratchpad saw nothing. The tiger saw everything.",
  "Wrong answer. I am not mad. I am… strategically concerned.",
  "Not correct. The family legacy is patient. I am less patient.",
  "Wrong. That answer was wrong. Your comeback starts now.",
  "Incorrect. The tiger parent is already thinking about problem number two.",
  "Nope. Wrong. Practice until your cousin asks YOU for help.",
  "Wrong. I love you. I do not love skipping steps.",
  "Incorrect. The answer was not that. The answer is still available. Go get it.",
  "Wrong answer. The family honor sends its regards. And a worksheet.",
  "Not quite. Read the question. Respect the question. Fear the question a little.",
  "Wrong. Your sibling is being supportive. I am being a tiger parent.",
  "Incorrect. The Kumon spirits are disappointed. I channel their energy.",
  "Nope. That was wrong. The good news: every wrong answer is practice in disguise.",
  "Wrong. Your cousin didn't hesitate. You hesitated wrong.",
  "Incorrect. I was ready to be proud. I'm ready to be persistent instead.",
  "Wrong answer. The tiger parent is not giving up. Neither should you.",
  "Not correct. Show your work. Show your heart. Show the right numbers.",
  "Wrong. The family group chat can wait. Your accuracy cannot.",
  "Incorrect. The scratchpad is empty. Your brain should not be.",
  "Nope. Wrong. Round two. Fight.",
];
