import type { SourceRegistryEntry } from "./source-registry";

/** Additional sources from product spec (A–E). Merged into SOURCE_REGISTRY. */
export const SOURCE_REGISTRY_EXTENDED: SourceRegistryEntry[] = [
  // A — Official / benchmark (beyond core NY/TX/NYSED registry entries)
  {
    id: "va-sol-released",
    name: "Virginia SOL Released Tests",
    shortName: "VA SOL",
    sourceType: "OFFICIAL_RELEASED",
    publisher: "Virginia Department of Education",
    jurisdiction: "VA",
    url: "https://www.doe.virginia.gov/teaching-learning-assessment/student-assessment",
    importStatus: "FULL_IMPORT_ALLOWED",
    canStoreFullText: true,
    canDisplayToStudents: true,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
    attributionText: "© Virginia Department of Education — SOL released items",
  },
  {
    id: "sbac-caaspp-practice",
    name: "Smarter Balanced / CAASPP Practice Tests",
    shortName: "SBAC/CAASPP",
    sourceType: "OFFICIAL_RELEASED",
    publisher: "Smarter Balanced Assessment Consortium",
    jurisdiction: "US",
    url: "https://www.caaspp-elpac.org/resources/preparation/practice-and-training-tests/",
    importStatus: "FULL_IMPORT_ALLOWED",
    canStoreFullText: true,
    canDisplayToStudents: true,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
    notes: "Practice tests and scoring guides via state SBAC portals.",
  },
  {
    id: "college-board-educator-qbank",
    name: "College Board Educator Question Bank",
    shortName: "CB Educator",
    sourceType: "OFFICIAL_LINKED",
    publisher: "College Board",
    url: "https://satsuite.collegeboard.org/",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
    notes: "No bulk export; link/manual tracking only.",
  },
  // B — OER / curriculum
  {
    id: "core-knowledge",
    name: "Core Knowledge",
    shortName: "Core Knowledge",
    sourceType: "OER",
    publisher: "Core Knowledge Foundation",
    url: "https://www.coreknowledge.org/curriculum/",
    licenseName: "CC BY-NC-SA",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
  },
  {
    id: "el-education",
    name: "EL Education / Open Up ELA",
    shortName: "EL Education",
    sourceType: "OER",
    publisher: "EL Education",
    url: "https://eleducation.org/",
    licenseName: "CC BY",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
  },
  {
    id: "openstax",
    name: "OpenStax",
    shortName: "OpenStax",
    sourceType: "OER",
    publisher: "OpenStax / Rice University",
    url: "https://openstax.org/",
    licenseName: "CC BY 4.0",
    licenseType: "CC-BY-4.0",
    importStatus: "FULL_IMPORT_ALLOWED",
    canStoreFullText: true,
    canDisplayToStudents: true,
    canModify: true,
    canRedistribute: true,
    attributionRequired: true,
    attributionText: "© OpenStax — CC BY 4.0",
  },
  {
    id: "ck12",
    name: "CK-12",
    shortName: "CK-12",
    sourceType: "OER",
    publisher: "CK-12 Foundation",
    url: "https://www.ck12.org/",
    licenseName: "CC BY-NC",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
  },
  {
    id: "phet",
    name: "PhET Interactive Simulations",
    shortName: "PhET",
    sourceType: "OER",
    publisher: "University of Colorado Boulder",
    url: "https://phet.colorado.edu/",
    licenseName: "CC BY 4.0",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
    notes: "Simulations — link out; not MCQ bank.",
  },
  {
    id: "easypeasy",
    name: "Easy Peasy All-in-One Homeschool",
    shortName: "Easy Peasy",
    sourceType: "OFFICIAL_LINKED",
    publisher: "Easy Peasy",
    url: "https://allinonehomeschool.com/",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
  },
  {
    id: "ambleside",
    name: "AmblesideOnline",
    shortName: "Ambleside",
    sourceType: "OFFICIAL_LINKED",
    publisher: "AmblesideOnline",
    url: "https://www.amblesideonline.org/",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
    notes: "Reading lists — link/manual tracking.",
  },
  // C — Reading (ReadWorks/CommonLit already in base registry)
  {
    id: "ckla",
    name: "Core Knowledge Language Arts",
    shortName: "CKLA",
    sourceType: "OER",
    publisher: "Amplify / Core Knowledge",
    url: "https://www.coreknowledge.org/curriculum/",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
  },
  // D — Math challenge
  {
    id: "beast-aops",
    name: "Beast Academy / Art of Problem Solving",
    shortName: "AoPS",
    sourceType: "LICENSED",
    publisher: "Art of Problem Solving",
    url: "https://beastacademy.com/",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
    notes: "Commercial — link or private upload only.",
  },
  {
    id: "webwork-opl",
    name: "WeBWorK Open Problem Library",
    shortName: "WeBWorK OPL",
    sourceType: "OER",
    publisher: "OpenWeBWorK Community",
    url: "https://github.com/openwebwork/webwork-open-problem-library",
    licenseName: "Open Problem Library License",
    importStatus: "FULL_IMPORT_ALLOWED",
    canStoreFullText: true,
    canDisplayToStudents: true,
    canModify: true,
    canRedistribute: true,
    attributionRequired: true,
    notes: "PG-format problems; sample import from OPL subset.",
  },
  {
    id: "eedi-kaggle",
    name: "Eedi / Kaggle Misconception Datasets",
    shortName: "Eedi",
    sourceType: "OER",
    publisher: "Eedi",
    url: "https://www.kaggle.com/competitions/eedi-mining-misconceptions-in-mathematics",
    importStatus: "NEEDS_REVIEW",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
    notes: "Competition terms — verify license before bulk import.",
  },
  {
    id: "mathcounts-amc",
    name: "MATHCOUNTS / AMC Style",
    shortName: "Contest Math",
    sourceType: "LICENSED",
    publisher: "Various",
    importStatus: "PRIVATE_UPLOAD_ONLY",
    canStoreFullText: true,
    canDisplayToStudents: true,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
    notes: "Manual upload only unless rights cleared.",
  },
  // E — Commercial / paid
  {
    id: "problem-attic",
    name: "Problem-Attic",
    shortName: "Problem-Attic",
    sourceType: "LICENSED",
    publisher: "Problem-Attic",
    url: "https://www.problem-attic.com/",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
  },
  {
    id: "ixl",
    name: "IXL",
    shortName: "IXL",
    sourceType: "LICENSED",
    publisher: "IXL Learning",
    url: "https://www.ixl.com/",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
  },
  {
    id: "zearn",
    name: "Zearn",
    shortName: "Zearn",
    sourceType: "LICENSED",
    publisher: "Zearn",
    url: "https://www.zearn.org/",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
  },
  {
    id: "teaching-textbooks",
    name: "Teaching Textbooks",
    shortName: "Teaching Textbooks",
    sourceType: "LICENSED",
    publisher: "Teaching Textbooks",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
  },
  {
    id: "math-mammoth",
    name: "Math Mammoth",
    shortName: "Math Mammoth",
    sourceType: "PARENT_PRIVATE_UPLOAD",
    publisher: "Math Mammoth",
    url: "https://www.mathmammoth.com/",
    importStatus: "PRIVATE_UPLOAD_ONLY",
    canStoreFullText: true,
    canDisplayToStudents: true,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
    notes: "Family PDF upload workflow.",
  },
  {
    id: "saxon",
    name: "Saxon Math",
    shortName: "Saxon",
    sourceType: "PARENT_PRIVATE_UPLOAD",
    publisher: "Saxon",
    importStatus: "PRIVATE_UPLOAD_ONLY",
    canStoreFullText: true,
    canDisplayToStudents: true,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
    notes: "Private upload/manual workflow.",
  },
  {
    id: "learnosity-mastery",
    name: "Learnosity / Mastery Item Bank",
    shortName: "Learnosity",
    sourceType: "LICENSED",
    publisher: "Learnosity",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
    notes: "Future paid integration.",
  },
  {
    id: "edcite",
    name: "Edcite",
    shortName: "Edcite",
    sourceType: "LICENSED",
    publisher: "Edcite",
    url: "https://www.edcite.com/",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
  },
];
