import type { ContentImportMode, ContentSourceRegistryType } from "@/generated/prisma/client";

export type SourceRegistryEntry = {
  id: string;
  name: string;
  shortName: string;
  sourceType: ContentSourceRegistryType;
  publisher?: string;
  jurisdiction?: string;
  url?: string;
  termsUrl?: string;
  licenseName?: string;
  licenseType?: string;
  importStatus: ContentImportMode;
  canStoreFullText: boolean;
  canDisplayToStudents: boolean;
  canModify: boolean;
  canRedistribute: boolean;
  attributionRequired: boolean;
  attributionText?: string;
  notes?: string;
};

/** Canonical registry of supported external content sources. */
export const SOURCE_REGISTRY: SourceRegistryEntry[] = [
  {
    id: "tea-staar",
    name: "TEA STAAR Released Items",
    shortName: "TEA STAAR",
    sourceType: "OFFICIAL_RELEASED",
    publisher: "Texas Education Agency",
    jurisdiction: "TX",
    url: "https://tea.texas.gov/student-assessment/staar/staar-released-test-questions",
    importStatus: "FULL_IMPORT_ALLOWED",
    canStoreFullText: true,
    canDisplayToStudents: true,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
    attributionText: "© Texas Education Agency — STAAR released items",
    notes: "Released questions, answer keys, rationales where published.",
  },
  {
    id: "nysed-released",
    name: "NYSED Released Questions",
    shortName: "NYSED",
    sourceType: "OFFICIAL_RELEASED",
    publisher: "New York State Education Department",
    jurisdiction: "NY",
    url: "https://www.nysedregents.org/",
    importStatus: "FULL_IMPORT_ALLOWED",
    canStoreFullText: true,
    canDisplayToStudents: true,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
  },
  {
    id: "college-board-sat-qbank",
    name: "College Board SAT Student Question Bank",
    shortName: "CB SAT QBank",
    sourceType: "OFFICIAL_LINKED",
    publisher: "College Board",
    url: "https://satsuite.collegeboard.org/practice",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
    notes: "Track performance manually; link out for official items.",
  },
  {
    id: "khan-sat",
    name: "Khan Academy Official SAT Prep",
    shortName: "Khan SAT",
    sourceType: "OFFICIAL_LINKED",
    publisher: "Khan Academy / College Board",
    url: "https://www.khanacademy.org/sat",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
  },
  {
    id: "illustrative-math",
    name: "Illustrative Mathematics / Open Up Resources",
    shortName: "Illustrative Math",
    sourceType: "OER",
    publisher: "Illustrative Mathematics",
    url: "https://im.kendallhunt.com/",
    licenseName: "CC BY 4.0",
    licenseType: "CC-BY-4.0",
    importStatus: "FULL_IMPORT_ALLOWED",
    canStoreFullText: true,
    canDisplayToStudents: true,
    canModify: true,
    canRedistribute: true,
    attributionRequired: true,
  },
  {
    id: "engageny",
    name: "EngageNY / UnboundEd",
    shortName: "EngageNY",
    sourceType: "OER",
    publisher: "NYSED / UnboundEd",
    url: "https://greatminds.org/math-curriculum",
    licenseName: "CC BY-NC-SA",
    importStatus: "FULL_IMPORT_ALLOWED",
    canStoreFullText: true,
    canDisplayToStudents: true,
    canModify: true,
    canRedistribute: false,
    attributionRequired: true,
  },
  {
    id: "readworks",
    name: "ReadWorks",
    shortName: "ReadWorks",
    sourceType: "OFFICIAL_LINKED",
    publisher: "ReadWorks",
    url: "https://www.readworks.org/",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
  },
  {
    id: "commonlit",
    name: "CommonLit",
    shortName: "CommonLit",
    sourceType: "OFFICIAL_LINKED",
    publisher: "CommonLit",
    url: "https://www.commonlit.org/",
    importStatus: "LINK_ONLY",
    canStoreFullText: false,
    canDisplayToStudents: false,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
  },
  {
    id: "tigerparent-generated",
    name: "TigerParent Generated Drills",
    shortName: "Generated",
    sourceType: "GENERATED",
    publisher: "TigerParent",
    importStatus: "FULL_IMPORT_ALLOWED",
    canStoreFullText: true,
    canDisplayToStudents: true,
    canModify: true,
    canRedistribute: false,
    attributionRequired: false,
    attributionText: "Generated practice item — not official exam content",
    notes: "Deterministic fluency drills only. Not for benchmarks or mastery certification.",
  },
  {
    id: "parent-private-upload",
    name: "Parent Private Upload",
    shortName: "Family Upload",
    sourceType: "PARENT_PRIVATE_UPLOAD",
    publisher: "Family",
    importStatus: "PRIVATE_UPLOAD_ONLY",
    canStoreFullText: true,
    canDisplayToStudents: true,
    canModify: true,
    canRedistribute: false,
    attributionRequired: false,
    notes: "Family-only materials uploaded by parent.",
  },
  {
    id: "gsm8k",
    name: "GSM8K Grade School Math",
    shortName: "GSM8K",
    sourceType: "OER",
    publisher: "OpenAI",
    url: "https://huggingface.co/datasets/openai/gsm8k",
    licenseName: "MIT",
    licenseType: "MIT",
    importStatus: "FULL_IMPORT_ALLOWED",
    canStoreFullText: true,
    canDisplayToStudents: true,
    canModify: true,
    canRedistribute: true,
    attributionRequired: true,
    attributionText: "OpenAI GSM8K dataset (MIT license) — human-authored word problems",
    notes: "Challenge/word-problem bank. Not official exam content.",
  },
  {
    id: "college-board-sat-pdf",
    name: "College Board SAT Practice Tests (PDF)",
    shortName: "CB SAT PDF",
    sourceType: "OFFICIAL_RELEASED",
    publisher: "College Board",
    url: "https://satsuite.collegeboard.org/practice/practice-tests/paper",
    importStatus: "FULL_IMPORT_ALLOWED",
    canStoreFullText: true,
    canDisplayToStudents: true,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
    attributionText: "© College Board — official SAT practice test",
    notes: "Official released practice tests with scoring guides.",
  },
  {
    id: "naep-released",
    name: "NAEP Released Questions",
    shortName: "NAEP",
    sourceType: "OFFICIAL_RELEASED",
    publisher: "NCES / NAEP",
    jurisdiction: "US",
    url: "https://www.nationsreportcard.gov/nqt/",
    importStatus: "FULL_IMPORT_ALLOWED",
    canStoreFullText: true,
    canDisplayToStudents: true,
    canModify: false,
    canRedistribute: false,
    attributionRequired: true,
    attributionText: "National Assessment of Educational Progress (NAEP) released item",
    notes: "National benchmark items from NAEP Questions Tool.",
  },
];

export function getSourceById(id: string) {
  return SOURCE_REGISTRY.find((s) => s.id === id);
}
